### ISSUE TITLE
Careful your .travis.yml has a TROJAN

### ISSUE THREAD

**Issue by IbrahimTanyalcin** [jankapunkt/latexcv#26]
I got a report from my antivirus software that the .travis.yml had HEUR:Trojan-Downloader.Shell.Agent.p . It might be a false positive so please double check it, if correct please upload a clean version including your own Git folder for the safety of others.

**Comment by jankapunkt** [comment]
Hi @IbrahimTanyalcin this is potentially a false positive. Let me explain the [`.travis.yml`file](https://github.com/jankapunkt/latexcv/blob/master/.travis.yml):

```yaml
# basic travis setup for a simple Ubuntu trusty container
sudo: true
dist: trusty
language: bash

# restrict build to certain branches
general:
  branches:
    only:
      - ci_setup

before_install:
  - PROJECTDIR=$(pwd)
   # this line below downloads tex-live distribution to the container
   # it uses a German Mirror from the Friedrich-Alexander University
   # we use a custom tex-live distribution because the trusty repo does not 
   # contain a texlive version that supports fontawesome, thus failing the builds
   # see https://tug.org/
   # see https://ctan.org/mirrors
  - cd /tmp && wget http://ftp.fau.de/ctan/systems/texlive/tlnet/install-tl-unx.tar.gz
   # unpacking the texlive unix distribution
   # and prepare for building
  - tar -xvzf install-tl-unx.tar.gz
  - cd install-tl-*
  - chmod +x install-tl
   # we install it using a given texlive.profile 
   # (see https://github.com/jankapunkt/latexcv/blob/master/texlive.profile)
   # and add it's executable to $PATH
   # if everything was successful, we can enter the pdflatex command
   # without any errors
  - sudo ./install-tl --profile=$PROJECTDIR/texlive.profile
  - PATH=/usr/local/texlive/2017/bin/x86_64-linux:$PATH
  - pdflatex -v
  - cd $PROJECTDIR

# finally run the test scripts from https://github.com/jankapunkt/latexcv/tree/master/tests
script:
  - bash tests/testall.sh
```

I will add a wiki entry in case other get this error message, too. If you still sceptical, you can set up a VM and execute everything by hand and record the traffic etc.
